andy_kalasini-taua/week5/moma-app/config/routes.rb
Rails.application.routes.draw do

#Artist CRUD

# Create ###################

# 1. new (blank form)
get '/artists/new' => 'artists#new', as: 'new_artist' #gives new_artist path

#2. creat (form submits here, add to DB, redirect)
post '/artists' => 'artists#create'# Read ################

#  1. index (all rows)
get '/artists' => 'artists#index'

# 2. show (details about one row, by ID)
get '/artists/:id' => 'artists#show', as: 'artist' # _path
# Update ###############

#  1. edit (show pre-populated form, i.e also get row gby ID)
get '/artists/:id/edit' => 'artists#edit', as: 'edit_artist'
# 2. update (form submits here, update DB, redirect to show)
#Because we are using the form _with form builder, it automatically submits edit forms (as opposed to new forms) using the moment 'patch' method, instead of 'post'
patch '/artists/:id' => 'artist#update'
# Delete ################

# 1. destroy (remove row from DB, redirect to index)
delete '/artists/:id' => 'artists#destroy' #same helper as show: artist_path(id)


#Works CRUD routes

resources :works







end #

andy_kalasini-taua/week5/moma-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

andy_kalasini-taua/week5/moma-app/app/models/artist.rb
class Artist < ApplicationRecord
  has_many :works
  # go to the works table and use [current class name plural] _id to find the matching ids for this artist
end

andy_kalasini-taua/week5/moma-app/app/models/work.rb
class Work < ApplicationRecord
  belongs_to :artist #Mandatory unless you add' , optional: true' use
end

andy_kalasini-taua/week5/moma-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

andy_kalasini-taua/week5/moma-app/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  # Create ###################

  # 1. new (blank form)
def new
 @artist = Artist.new
end

  #2. create (form submits here, add to DB, redirect)
def create
  # raise 'hell' force an error, so we can debug in the web console

#Try to just pass the hash of form values to .create - so much quicker!
  # Artist.create params[:artist]
  # NOT SECURE!! We dont just let through

  # Srong Params:
  # We write a method in the private section of this controller
  # which acts as a doorman to check the fields were passing in form the form via params - only the approved
  Artist.create artist_params

  redirect_to artists_path

end
  # Read ################

  #  1. index (all rows)
def index
 @artists = Artist.all
end

  # 2. show (details about one row, by ID)
def show
  @artist = Artist.find params[:id]
end
  # Update ###############

  #  1. edit (show pre-populated form, i.e also get row gby ID)
def edit
  @artist = Artist. find params[:id]
end
  # 2. update (form submits here, update DB, redirect to show)
def update
  artist = Artist.find params[:id]
  artist.update artist_params
  redirect_to artist_path(artist.id)
end
  # Delete ################

  # 1. destroy (remove row from DB, redirect to index)
def destroy
  Artist.destroy params[:id]
  redirect_to artists_path
end

 # methods defined below the privat heading are for internal use only by the actions of this controller;
 # this is, they are NOT the handlers for routes defined in routes.rb
private

def artist_params
  # Make sure the artist key is set and only let through the approved form fields from within that
  params.require(:artist).permit(:name, :nationality, :dob, :period, :roundness, :bio, :image)

end

end # ArtistsController

andy_kalasini-taua/week5/moma-app/app/controllers/works_controller.rb
class WorksController < ApplicationController


  def new
    @work = Work.new
  end

# create

  def create
    Work.create work_params
    redirect_to work_path
  end

# Read

  def index
    @works = Work.all
  end

  def show
    @work = Work.find params[:id]
  end

  def edit
    @work = Work.find params[:id]
  end

  def update
    work = Work.find params[:id]
    work.update work_params
    redirect_to work_path(work.id)
  end

  def destroy
  end

  private

def work_params
  params.require(:work).permit(:title, :year, :medium, :style, :image, :artist_id)
end

end

andy_kalasini-taua/week5/moma-app/app/helpers/application_helper.rb
module ApplicationHelper
end

andy_kalasini-taua/week5/moma-app/app/helpers/works_helper.rb
module WorksHelper
end

andy_kalasini-taua/week5/moma-app/app/views/artists/_form.html.erb
<%= form_with model: @artist, local: true do |f| %>


<%= f.label :name %>
<br>
<%= f.text_field :name %>
<br><br>

<%= f.label :nationality %>
<br>
<%= f.text_field :nationality %>
<br><br>

<%= f.label :dob, 'Date of Birth' %>
<br>
<%= f.date_field :dob %>
<br><br>

<%= f.label :period %>
<br>
<%= f.text_field :period %>
<br><br>

<%= f.label :image %>
<br>
<%= f.text_field :image %>
<br><br>

<%= f.label :roundness %>
<br>
<%= f.text_field :roundness %>
<br><br>

<%= f.label :bio %>
<br>
<%= f.text_field :bio %>
<br><br>

<%= f.submit %>

<% end  %>

andy_kalasini-taua/week5/moma-app/app/views/artists/edit.html.erb
<h2></h2>

andy_kalasini-taua/week5/moma-app/app/views/artists/index.html.erb
<h2>Index of Artists</h2>

list goes here
<ul>
  <% @artists.each do |artist| %>
  <li>
    <%= link_to artist.name, artist_path(artist.id)  %>
  </li>
  <% end %>
</ul>

andy_kalasini-taua/week5/moma-app/app/views/artists/new.html.erb
<h2>Add New Artist</h2>

<%= render partial: 'form' %>

andy_kalasini-taua/week5/moma-app/app/views/artists/show.html.erb
<h2>
  <%=  @artist.name %>
</h2>



<%= link_to 'Edit Artist', edit_artist_path %>

<%= link_to 'Delete Artist', artist_path(@artist.id), method: 'delete' %>

<p>
 <strong>Nationality</strong>:
 <%= @artist.nationality %>
</p>

<p>
<strong>Period</strong>:
<%= @artist.period %>
</p>

<p>
 <strong>Roundness</strong>:
<%= @artist.roundness %>
</p>

<p>
 <strong>Bio</strong>:
 <%= @artist.bio %>
</p>

 <ul>
   <% @artist.works.each do |work| %>
 <li>
<%= link_to work.title, work_path(work.id) %>
 </li>

<% end %>
</ul>


<%= image_tag @artist.image, alt: "Photo of #{@artist.name}", class: 'artist' %>

andy_kalasini-taua/week5/moma-app/app/views/works/_form.html.erb
<%= form_with model: @work, local: true do |f| %>

  <%= f.label :title %><br>
  <%= f.text_field :title %><br><br>

  <%= f.label :year %><br>
  <%= f.text_field :year %><br><br>

  <%= f.label :medium %><br>
  <%= f.text_field :medium %><br><br>

  <%= f.label :style %><br>
  <%= f.text_field :style %><br><br>

  <%= f.label :image, 'Image URL' %><br>
  <%= f.text_field :image %><br><br>

  <!-- TODO: should be a dropdown! The users don't know the IDs! -->
  <!-- Research 'collection_select' helper -->
  <%= f.label :artist_id %><br>
  <%= f.text_field :artist_id %><br><br>

  <%= f.submit %>

<% end %>

andy_kalasini-taua/week5/moma-app/app/views/works/edit.html.erb
<h2>Edit <%= @work.title %></h2>

<%= render partial: 'form' %>

andy_kalasini-taua/week5/moma-app/app/views/works/index.html.erb
<ul>
  <% @works.each do |work| %>
  <li>
  <%= link_to work.title, work_path(work.id) %>
  </li>
  <% end %>
</ul>

andy_kalasini-taua/week5/moma-app/app/views/works/new.html.erb
<h2>Add new work</h2>

<%= render partial: 'form' %>

andy_kalasini-taua/week5/moma-app/app/views/works/show.html.erb
<h2>
<em>
<%= @work.title %>,
</em>,
<%= @work.year %>
</h2>
<%= link_to 'Edit This Work', edit_work_path(@work.id) %>

<%= link_to 'Delete This Work', work_path(@work.id), method: 'delete' %>

<p>
  <strong>Artist:</strong>
  <%= link_to @work.artist.name, artists_path(@work.artist.id) %>
</p>

<p>
  <strong>Medium</strong>:
  <%=  @work.medium %>
</p>

<p>
 <strong>Style</strong>
 <%= @work.style %>
</p>

<%= image_tag @work.image, alt: @work.title, class: 'work' %>

andy_kalasini-taua/week5/moma-app/app/views/works/update.html.erb
<h1>Works#update</h1>
<p>Find me in app/views/works/update.html.erb</p>