sam_skinner/week5/websites/config/routes.rb
Rails.application.routes.draw do
  # Websites Routes
  resources :websites

  # Frontends Routes
  resources :frontends

  # Backends Routes
  resources :backends
end

sam_skinner/week5/websites/app/models/backend.rb
class Backend < ApplicationRecord
  has_many :websites
end

sam_skinner/week5/websites/app/models/frontend.rb
class Frontend < ApplicationRecord
  has_many :websites
end

sam_skinner/week5/websites/app/models/website.rb
class Website < ApplicationRecord
  belongs_to :frontend
  belongs_to :backend
end

sam_skinner/week5/websites/app/controllers/backends_controller.rb
class BackendsController < ApplicationController
  # CREATE
  def new
    @backend = Backend.new
  end

  def create
    Backend.create backend_params
    redirect_to backends_path
  end

  # READ
  def index
    @backends = Backend.all
  end

  def show
    @backend = Backend.find params[:id]
  end

  # UPDATE
  def edit
    @backend = Backend.find params[:id]
  end

  def update
    backend = Backend.find params[:id]
    backend.update backend_params
    redirect_to backend_path(backend.id)
  end

  # DESTROY
  def destroy
    Backend.destroy params[:id]
    redirect_to backends_path
  end

  private

  def backend_params
    params.require(:backend).permit(:name, :date_released, :logo)
  end
end

sam_skinner/week5/websites/app/controllers/frontends_controller.rb
class FrontendsController < ApplicationController
  # CREATE
  def new
    @frontend = Frontend.new
  end

  def create
    Frontend.create frontend_params
    redirect_to frontends_path
  end

  # READ
  def index
    @frontends = Frontend.all
  end

  def show
    @frontend = Frontend.find params[:id]
  end

  # UPDATE
  def edit
    @frontend = Frontend.find params[:id]
  end

  def update
    frontend = Frontend.find params[:id]
    frontend.update frontend_params
    redirect_to frontend_path(frontend.id)
  end

  # DESTROY
  def destroy
    Frontend.destroy params[:id]
    redirect_to frontends_path
  end

  private

  def frontend_params
    params.require(:frontend).permit(:name, :date_released, :logo)
  end
end

sam_skinner/week5/websites/app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  # CREATE
  def new
    @website = Website.new
  end

  def create
    Website.create website_params
    redirect_to websites_path
  end

  # READ
  def index
    @websites = Website.all
  end

  def show
    @website = Website.find params[:id]
    @hacked = @website.hacked ? 'Yes' : 'No'
  end

  # UPDATE
  def edit
    @website = Website.find params[:id]
  end

  def update
    website = Website.find params[:id]
    website.update website_params
    redirect_to website_path(website.id)
  end

  # DESTROY
  def destroy
    Website.destroy params[:id]
    redirect_to websites_path
  end

  private

  def website_params
    params.require(:website).permit(:name, :frontend_id, :backend_id, :launched, :hacked, :domain, :owned_by, :wiki)
  end
end

sam_skinner/week5/websites/app/helpers/backends_helper.rb
module BackendsHelper
end

sam_skinner/week5/websites/app/helpers/frontends_helper.rb
module FrontendsHelper
end

sam_skinner/week5/websites/app/helpers/websites_helper.rb
module WebsitesHelper
end

sam_skinner/week5/websites/app/views/frontends/_form.html.erb
<%= form_with model: @frontend, local: true do |f| %>

<%= f.label :name %><br>
<%= f.text_field :name %><br><br>

<%= f.label :date_released, 'Year Released' %><br>
<%= f.text_field :date_released %><br><br>

<%= f.label :logo %><br>
<%= f.text_field :logo %><br><br>

<%= f.submit %>

<% end %>

sam_skinner/week5/websites/app/views/frontends/edit.html.erb
<h2>Edit: <%= @frontend.name %></h2>

<%= render partial: 'form' %>

sam_skinner/week5/websites/app/views/frontends/index.html.erb
<h2>Index of Frontends</h2>

<ul>
<% @frontends.each do |f| %>
  <li>
    <%= link_to f.name, frontend_path(f.id) %> - <%= f.date_released %>
  </li>
<% end %>
</ul>

sam_skinner/week5/websites/app/views/frontends/new.html.erb
<h2>Create New Frontend</h2>

<%= render partial: 'form' %>

sam_skinner/week5/websites/app/views/frontends/show.html.erb
<h2><%= @frontend.name %></h2>

<%= link_to 'Edit Frontend', edit_frontend_path %>
|
<%= link_to 'Delete Frontend', frontend_path(@frontend.id), method: 'delete' %>

<p></p>

<%= image_tag @frontend.logo, alt: "#{@frontend.name} logo", class: 'logo' %>

<p>
  <strong>Year Launched: </strong>
  <%= @frontend.date_released %>
</p>

<strong>Used In:</strong>
<ul>
  <% @frontend.websites.each do |w| %>
  <li>
    <%= link_to w.name, website_path(w.id) %> - <%= w.launched %>
  </li>
  <% end %>
</ul>