amanda_jarvinen/week_05/creativeco-app/config/routes.rb
Rails.application.routes.draw do

  root :to => "creations#index"

  # Coders
  resources :coders

  # Creations
  resources :creations
end

amanda_jarvinen/week_05/creativeco-app/app/models/coder.rb
class Coder < ApplicationRecord
    has_many :creations
end

amanda_jarvinen/week_05/creativeco-app/app/models/creation.rb
class Creation < ApplicationRecord
    belongs_to :coder
end

amanda_jarvinen/week_05/creativeco-app/app/controllers/coders_controller.rb
class CodersController < ApplicationController
  def new
    @coder = Coder.new
  end

  def create
    Coder.create coder_params
    redirect_to coders_path
  end

  def index
    @coders = Coder.all
  end

  def show
    @coder = Coder.find params[:id]
  end

  def edit
    @coder = Coder.find params[:id]
  end

  def update
    coder = Coder.find params[:id]
    coder.update coder_params
    redirect_to coder_path(coder.id)
  end

  def destroy
    Coder.destroy params[:id]
    redirect_to coders_path # back to index
  end

  def coder_params
    params.require(:coder).permit(:name, :nationality, :image_url, :bio, :portfolio_url, :instagram_url)
  end
end

amanda_jarvinen/week_05/creativeco-app/app/controllers/creations_controller.rb
class CreationsController < ApplicationController
  def new
    @creation = Creation.new
  end

  def create
    Creation.create creation_params
    redirect_to creations_path
  end

  def index
    @creations = Creation.all
  end

  def show
    @creation = Creation.find params[:id]
  end

  def edit
    @creation = Creation.find params[:id]
  end

  def update
    creation = Creation.find params[:id]
    creation.update creation_params
    redirect_to creation_path(creation.id)
  end

  def destroy
    Creation.destroy params[:id]
    redirect_to creations_path # back to index
  end

  def creation_params
    params.require(:creation).permit(:title, :medium, :image_url, :coder_id)
  end

end

amanda_jarvinen/week_05/creativeco-app/app/helpers/coders_helper.rb
module CodersHelper
end

amanda_jarvinen/week_05/creativeco-app/app/helpers/creations_helper.rb
module CreationsHelper
end

amanda_jarvinen/week_05/creativeco-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CreativecoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header>
      <nav>
        <h1>Creative Coders</h1>
        <%= link_to 'Gallery', creations_path %>
        |
        <%= link_to 'Add new creation', new_creation_path %>
        |
        <%= link_to 'Coders', coders_path %>
        |
        <%= link_to 'Add new coder', new_coder_path %>
      </nav>
      <hr>
    </header>
    <main>
     <%= yield %>
    </main>
    <footer>
    <hr>
      &copy; Creative Coders Create Cool Code, 2020
    </footer>
  </body>
</html>